### ISSUE TITLE
tlvfile execution issue

### ISSUE THREAD

**Issue by Tomer-ke** [usecallmanagernz/certutils#1]
Hi,
when i try to run the script to create ITLfile.tlv, the code send error code, see below 2 examples.

No -r/--record argument supplied for ccm
tom:/mnt/c/linux/certutils-master$ ./tlvfile -b ./ITLFile.tlv -c CA.pem \-r asterisk.pem -f ccm -r apache.pem -f https
Unsupported HEADER_DIGEST_ALGORITHM: SHA1
tom:/mnt/c/linux/certutils-master$ ./tlvfile -b ./ITLFile.tlv -d sha256 -c CA.pem -r asterisk.pem -f ccm -r apache.pem -f https
Unsupported RECORD_FUNCTION: SAST

can you please advise?

thanks
Tomer

**Comment by gareth-palmer** [comment]
There was an issue with the handling of the digest and function arguments.

This has been fixed in master and in v2.1 of certutils. Please download the latest version and re-test.

Documentation website also used inconsistent captialization of those arguments and that has been fixed too.
