### ISSUE TITLE
Another tlvfile Execution Issue

### ISSUE THREAD

**Issue by mbielech5** [usecallmanagernz/certutils#3]
Hi,

I am trying to create certificate files on a FreePBX v16 system that was installed with the FreePBX distro.

I used the following commands to install the certutils within the Sangoma OS (CentOS):

```
yum install python36u-pip
ln -s /usr/bin/python3.6 /usr/bin/python3
python3 -m pip install --upgrade pip
yum install git asterisk-devel
cd /usr/src
git clone https://github.com/usecallmanagernz/certutils.git certutils
cd certutils
```

When I try to run the script to create a ITLFile.tlv, I get an error at line 659 in main and line 380 in build_tlv_file when running this command:
```
sudo ./tlvfile --build /tftpboot/ITLFile.tlv --sast /etc/pki/tls/certs/sast.pem --ccm /etc/asterisk/keys/asterisk.pem --app-server /etc/pki/tls/certs/apache.pem
```
```
Traceback (most recent call last):
  File "./tlvfile", line 659, in main
    build_tlv_file(tlv_file, sast_certificate_file, version, hash_algorithm, filename, certificate_records)
  File "./tlvfile", line 380, in build_tlv_file
    signer_name += (';' if len(signer_name) else '') + attribute.rfc4514_string()
AttributeError: 'NameAttribute' object has no attribute 'rfc4514_string'
```

Am I doing something incorrect? Am I missing a dependency or something? Please let me know.

Kind Regards,
-Mark

**Comment by gareth-palmer** [comment]
Hello,

You are getting that error message because the version of the python `cryptography` library is lower than 2.5. Try installing the latest version using pip3 and re-test.

Gareth

**Comment by mbielech5** [comment]
Hi there,

Yep, that was the ticket! I used the following commands to update both Pip3 libraries below:
```
pip3 install --upgrade cryptography
pip3 install --upgrade lxml
```

Thank you for all the work you've done with this project. It has been greatly helpful in using Cisco phone with an open-source, Asterisk-based PBX!

Cheers,
-Mark
