### ISSUE TITLE
can't seem to sign the Desktop list for 88xx phone. An error results (RESOLVED)

### ISSUE THREAD

**Issue by ecrode** [usecallmanagernz/certutils#4]
I'm trying to secure remote access without resorting to a full VPN setup. As such I was able to get ITL* files working and phone provisioned via HTTPS. The issue is that it still seeks Desktop list file:  /Desktops/800x480x24/List.xml.sgn over an unencrypted 6970 port.
Personally I don't care about Desktop lists being exposed without encryption, but rerouting .sgn to plain .xml doesn't seem to work. Phone gets the file, but rejects it due to failure of signer verification:
 
> 6969 ERR May 13 01:10:35.320156 (338-6833) downd-AUTH: TLV 1 has 'T' 0x3c, must be 0x01
6970 ERR May 13 01:10:35.320180 (338-6833) downd-Initialize TLVTab failed
6971 ERR May 13 01:10:35.320231 (338-6833) downd-authVerifyFileBySigner FAILED

I've tried to sign it using the tftp (elliptic curve) cert which works for the 6971 port, but getting the following error:

> sudo ./sgnfile --build ../tftp/List.xml --tftp ../pbxcerts/nginx-ec-cert.pem --filename Desktops/800x480x24/List.xml.sgn
Traceback (most recent call last):
  File "./sgnfile", line 445, in main
    build_sgn_file(input_file, tftp_certificate_file, hash_algorithm, filename)
  File "./sgnfile", line 321, in build_sgn_file
    tlv_data += struct.pack('> B H B', HEADER_SIGNATURE_MODULUS, 1, [64, 128, 256, 512].index(signature_length))
ValueError: 48 is not in list

Error seems to indicate that signature length of 48 (bytes?) is not supported. Editing the script to add 48 as an option to the 0th / first position results in a different error:

> Traceback (most recent call last):
  File "./sgnfile", line 445, in main
    build_sgn_file(input_file, tftp_certificate_file, hash_algorithm, filename)
  File "./sgnfile", line 346, in build_sgn_file
    signature = private_key.sign(tlv_data, padding.PKCS1v15(), hash)
TypeError: sign() takes 3 positional arguments but 4 were given

File itself is pretty small:
```
<CiscoIPPhoneImageList>
<ImageItem Image="TFTP:Desktops/800x480x24/dark-139x109.png" URL="TFTP:Desktops/800x480x24/dark.png"/>
<ImageItem Image="TFTP:Desktops/800x480x24/light-139x109.png" URL="TFTP:Desktops/800x480x24/light.png"/>
</CiscoIPPhoneImageList>
```

So, I'm stuck having to sign a file I don't care about, and unable to do so. Any advice is really appreciated.

**Comment by ecrode** [comment]
I've just reread the page about Device Security, and see now that I'll need to create a secondary RSA TFTP cert to use specifically for file signing. I'll try to add it as a second tftp cert to the ITL* file and go from there. Sometimes I miss things that were stated in favor following the example code, I'll try to be more careful next time.
In any case I'll report back my findings in the morning.

**Comment by ecrode** [comment]
Ok, it worked. I've created an RSA cert and added it as a second TFTP cert to the ITL* file. Phone shows both in the trusted list menu.
> ./mkcert --common "co.sign" --organization "co" --unit "Auth" ../pbxcerts/sign.pem
> ./tlvfile --build ../tftp/ITLSEPxxx.tlv --version 1.1 --sast ../pbxcerts/sast.pem --ccm ../pbxcerts/asterisk-keys.pem --app-server ../pbxcerts/nginx-app-cert.pem --tftp ../pbxcerts/nginx-ec-cert.pem --tftp ../pbxcerts/sign.pem --filename ITLFile.tlv

The sngfile command worked without issue with RSA cert and I've uploaded sgn file to the server, which was sent to the phone
> ./sgnfile --build ../tftp/List.xml --tftp ../pbxcerts/sign.pem --filename Desktops/800x480x24/List.xml.sgn

Phone has now accepted the file, but seems that each of the images will have to be signed as well.
At least I now know what went wrong, it was clearly stated so I apologize for my lack of attention.

**Comment by ecrode** [comment]
Please close this issue as it is resolved. But please make it clearer that a second TFTP, specifically one that's not EC, certificate is needed to sign the files, such as desktop wallpapers. Alternately code would be updated to support file signing with an EC cert if such thing is possible.

**Comment by gareth-palmer** [comment]
Good to hear you got it working.

tlvfile and sgnfile will be updated to check that the keys provided are RSA.

The phone's behaviour when using encrypted provisioning is very non-obvious, so the documentation will also be updated to make that clearer.
