### ISSUE TITLE
Phone is having hard time accepting an EC TFTP cert for port 6971 transfer (possible fix included)

### ISSUE THREAD

**Issue by ecrode** [usecallmanagernz/certutils#5]
I've been working with ITL files to secure remote access to the phones (mainly I need it for HTTPs access to remote apps).
While at it I've been having a hard time getting the phone to accept and use TFTP certs and realized that it may be due to the sequence of their generation. 
Usually, one would start with generating a 20-year SAST certificate first to sign the ITL files, but TFTP certificate and the rest which are generated seconds later are made 20 years as well by default.
I think issue is that phone sees that signing cert expires first and thereby invalidates TFTP cert internally.

Changing the secondary certs to a 15 year limit (by adding '--years 15' parameter) seem to have solved the issue and the phone has no issues accepting a TFTP cert signed by a longer lived SAST cert.

If my theory holds true, documentation or default certificate validity period can be updated.

On related note, expanding on a previous resolved issue, documentation can be updated to use --ccm-tftp certificate option by default, in lieu of plain --ccm, which generates one RSA cert for file signing as well as asterisk access.

```
~/certutils-X.X$ sudo ./tlvfile --build /var/lib/tftpboot/ITLFile.tlv --version 1.1 --sast /etc/ssl/private/sast.pem \
  --ccm-tftp /etc/asterisk/keys/asterisk.pem --tftp /etc/apache2/ssl-certs/apache-ec.pem
```

**Comment by ecrode** [comment]
I think tlvfile could have an error / test to check if SAST cert expires prior to any others, in which case phone seems to invalidate the corresponding cert(s). I've tested it with tftp and app-server certificates and as long as they expire prior to SAST, they work, otherwise they fail without a clear indication why (must be the expiration date).
One solution I found was to generate my SAST with 99 year lifespan. This seem to have solved the issue with the default 20 year child certs.

**Comment by ecrode** [comment]
Can I just add that TFTP certificate and version 1.1 of tlv file doesn't really solve any security problems by itself. Creating a secure 6971 channel does not negate the fact that the phone exposes the mac address by first requesting /CTLSEP*mac*.tlv file from an unencrypted port, and a man in the middle can then interpolate that the ITLSEP*mac* file can be requested directly.
I now realize that TFTP path lead to a rabbit hole without a carrot at the end, and I can secure APP-SERVER without securing TFTP itself (and having to needlessly sign all of the public files).
The proper path to security seems to lie via CAPF certificates and actual encryption of cnf.xml files as described here:
https://www.cisco.com/c/en/us/support/docs/unified-communications/unified-communications-manager-callmanager/118929-technote-cucm-00.html
For now, I've resorted to making the cnf.xml file available upon request. Thankfully the 88xx phones seem to store the configuration between reboots and use cached file whenever configuration is not available from the server. Thereby I can make config file available for a limited time, prevision the phone(s) and delete the files.
Given enough time I hope to port your work into PHP and/or docker containers to make configuration only available via .cnf.xml.enc.sgn files. Meanwhile thank you for providing all of the tools needed to secure the remote access.

**Comment by gareth-palmer** [comment]
You could use the combined CCM+TFTP role if you want to only use RSA keys as the phone's do support EC keys for SIP-TLS. RSA keys are required for any `.tlv` file signing, so SAST and TFTP.

**Comment by gareth-palmer** [comment]
tlvfile, sgnfile etc. now check that the supplied keys are either RSA or EC.

Website documentation has been updated.
